export const TOGGLE_ROOM_LIST = "TOOGLE_ROOMLIST";
export const TOGGLE_CURRENT_ROOM_MSG = "TOGGLE_CURRENT_ROOM_MSG";
export const TOGGLE_MY_INFO = "TOGGLE_MY_INFO";
export const INIT_MY_INFO = "INIT_MY_INFO";
export const INIT_JOINED_ROOMS = "INIT_ROOMS";
export const INIT_MESSAGES = "INIT_MESSAGES";
export const SWITCH_ROOM = "SWITCH_ROOM";
export const ADD_MESSAGE = "ADD_MESSAGE";
